### ISSUE TITLE
Show Archive: Safari buffers the full length of the episodes

### ISSUE THREAD

**Issue by elgordino** [DNIStream/dni.website#39]
When show list page load Safari promptly downloads the full length of each episode in 64kb chunks. You can see the progress bar fill up and there are 1000's of requests in the debugger.

**Comment by Bidthedog** [comment]
Thanks @elgordino - currently only loads the first part in Chrome. Will have to change the way the HTML5 tag is initialised via the app, as I don't seem to have control over how the data is buffered via the tag attributes.

This is likely to go away with #33 as the whole show listing page is going to get a make over :)
