### ISSUE TITLE
Show Archive: Check for duplications when show added to YT playlist.

### ISSUE THREAD

**Issue by sudomistress** [DNIStream/dni.website#44]
We ran into an odd issue with Episode v5.2 where by adding the YT video to the Full Playlist, it duplicated the show on the website. We may want to add a check in the code for instances like this to prevent it in the future.

**Comment by sudomistress** [comment]
We believe the isssue is on YT's side at the moment, and a remove/readd to the playlist seemed to fix it.

**Comment by Bidthedog** [comment]
Having thought about this a little bit it's probably best that we're informed when this happens - a duplicate in the "Full Episodes" playlist is a bug with YT and will show a duplicate on the website too. Ignoring this means that we would have one or more YT playlists with duplicates in them.

I might remove duplicates for the website, but also send a warning email to us to highlight it. We'd get spammed a bit, as we'd receive an email every time someone looked at the website while the duplicate exists.
