### ISSUE TITLE
Episode version numbers confuse website.

### ISSUE THREAD

**Issue by sudomistress** [DNIStream/dni.website#53]
When a version has a zero added to it, like v2.10, it replaces the content of v2.1.

**Comment by Bidthedog** [comment]
Seems to duplicate the content - using the 2.1 content for one, and 2.10 content for the other.

Bad regex probably. Bad developer :( /slap

![image](https://user-images.githubusercontent.com/1425696/61533120-ccea5f80-aa23-11e9-8964-ed40f40794fb.png)

I'll look at this ASAP.
